### ISSUE TITLE
def get_five_day_forecast(data) in forecasts.pyhas stopped working

### ISSUE THREAD

**Issue by matbor** [claws/txBOM#2]
FYI,

```def get_five_day_forecast(data):```

function has stopped working in ```forecasts.py```, about 20-days ago, BOM must of changed the format again.

```
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "retrieve_forecast_v2.py", line 26, in demo
    forecastDict = txbom.forecasts.forecastToDict(forecast)
  File "/usr/local/lib/python2.7/dist-packages/txbom/forecasts.py", line 552, in forecastToDict
    next_five_days = get_five_day_forecast(forecast)
  File "/usr/local/lib/python2.7/dist-packages/txbom/forecasts.py", line 508, in get_five_day_forecast
    day_name, precis, temperature_min, temperature_max = items
exceptions.ValueError: need more than 0 values to unpack
```

Commenting out lines [552](https://github.com/claws/txBOM/blob/master/txbom/forecasts.py#L552) and [574](https://github.com/claws/txBOM/blob/master/txbom/forecasts.py#L574) in ```forecasts.py``` is a temporary fix until I work out the problem.

**Comment by claws** [comment]
Thanks for letting me know. It looks like the format has slightly changed. I've applied a fix which works for me but there seems a lot of variability in the format that it might just work for me. @matbor, could you see if the latest version works for you? If it does I'll close out this issue.

**Comment by matbor** [comment]
Thanks, looks like it is working.
